rich-content.md instagram/twitter/vimeo 无法联网需删除或代理
Building sites … ERROR 2020/10/11 21:35:27 Failed to get JSON resource "https:/
/api.instagram.com/oembed/?url=https://www.instagram.com/p/BGvuInzyFAe/&amp;maxw
idth=640&amp;omitscript=true": Get https://api.instagram.com/oembed/?url=https:/
/www.instagram.com/p/BGvuInzyFAe/&amp;maxwidth=640&amp;omitscript=true: dial tcp
 8.7.198.45:443: connectex: A connection attempt failed because the connected pa
rty did not properly respond after a period of time, or established connection f
ailed because connected host has failed to respond.
ERROR 2020/10/11 21:35:46 Failed to get JSON resource "https://api.twitter.com/1
/statuses/oembed.json?id=1085870671291310081&omit_script=true": Get https://api.
twitter.com/1/statuses/oembed.json?id=1085870671291310081&omit_script=true: dial
 tcp 108.160.170.52:443: connectex: A connection attempt failed because the conn
ected party did not properly respond after a period of time, or established conn
ection failed because connected host has failed to respond.
ERROR 2020/10/11 21:36:07 Failed to get JSON resource "https://vimeo.com/api/oem
bed.json?url=https://vimeo.com/48912912": Get https://vimeo.com/api/oembed.json?
url=https://vimeo.com/48912912: dial tcp 202.160.128.16:443: connectex: A connec
tion attempt failed because the connected party did not properly respond after a
 period of time, or established connection failed because connected host has fai
led to respond.
Built in 62651 ms
Error: Error building site: logged 3 error(s)